### ISSUE TITLE
Use nodiverse to manage the 'world'

### ISSUE THREAD

**Issue by marado** [envis10n/yadge#1]
Nodiverse, https://www.npmjs.com/package/nodiverse , is a JS library that allows you to define and manage a world. It manages the creation of tiles and passages, validation of coordinates and other things that you could probably benefit from without having to write new world models, as you are currently doing on yadge.

**Comment by envis10n** [comment]
Appreciate the input! I saw this yesterday, and I will give it some consideration. I'm really focused on learning and growing by writing the systems from the ground up.

I would also be more inclined to use nodiverse if it provided type defs.
